orbs:
  orb-tools: circleci/orb-tools@9.1.0
  hello-world: uraway/hello-world@<<pipeline.parameters.dev-orb-version>>

parameters:
  dev-orb-version:
    default: 'dev:alpha'
    type: string
  run-integration-tests:
    default: false
    type: boolean

jobs:
  integration-tests:
    executor: hello-world/default
    steps:
      - checkout
      - hello-world/echo-command

version: 2.1
workflows:
  integration-tests:
    when: << pipeline.parameters.run-integration-tests >> # パイプラインパラメータrun-integration-testsがtrueでなければ実行しない
    jobs:
      - integration-tests
  trigger-integration-tests-workflow:
    unless: << pipeline.parameters.run-integration-tests >> # パイプラインパラメータrun-integration-testsがtrueであれば実行しない
    jobs:
      - orb-tools/pack
      - orb-tools/publish-dev:
          orb-name: uraway/hello-world
          requires:
            - orb-tools/pack
      - orb-tools/trigger-integration-tests-workflow:
          requires:
            - orb-tools/publish-dev
