orbs:
  orb-tools: circleci/orb-tools@9.1.0

version: 2.1
workflows:
  promote-orb:
    jobs:
      - orb-tools/dev-promote-prod-from-commit-subject:
          fail-if-semver-not-indicated: true
          add-pr-comment: true
          bot-user: <botユーザー>
          bot-token-variable: PR_COMMENTER_GITHUB_TOKEN
          publish-version-tag: true
          ssh-fingerprints: 22:48:71:91:33:11:12:ab:f7:81:0f:1d:36:5a:44:34
          orb-name: uraway/hello-world
