orbs:
  orb-tools: circleci/orb-tools@9.3.1
  hello-world: sample-orbs/hello-world@<<pipeline.parameters.dev-orb-version>>

parameters:
  dev-orb-version:
    default: 'dev:alpha'
    type: string
  run-integration-tests: (d1)
    default: false
    type: boolean

jobs:
  integration-tests:
    executor: hello-world/default
    steps:
      - checkout
      - hello-world/echo-command

version: 2.1
workflows:
  integration-tests: (d2)
    when: << pipeline.parameters.run-integration-tests >> # パイプラインパラメータrun-integration-testsがtrueでなければ実行しない
    jobs:
      - integration-tests
  trigger-integration-tests-workflow: (d3)
    unless: << pipeline.parameters.run-integration-tests >> # パイプラインパラメータrun-integration-testsがtrueであれば実行しない
    jobs:
      - orb-tools/pack
      - orb-tools/publish-dev:
          orb-name: sample-orbs/hello-world
          requires:
            - orb-tools/pack
      - orb-tools/trigger-integration-tests-workflow:
          requires:
            - orb-tools/publish-dev
