version: 2.1

orbs:
  cli: circleci/circleci-cli@0.1.5

jobs:
    execution:
      machine: true
      steps:
        - cli/install
        - checkout
        - run:
            name: 展開
            command: circleci config process .circleci/test.yml > .circleci/2.0.yml
        - run:
            name: ランタイムテスト
            command: circleci local execute --config .circleci/2.0.yml --job hello-world/echo-job | tee local_build_output.txt /dev/stderr | tail -n 1 | grep "Success"

workflows:
  main:
    jobs:
      - execution
