orbs:
  orb-tools: circleci/orb-tools@8.27.4

version: 2.1
workflows:
  publish-dev-orb:
    jobs:
      - orb-tools/pack
      - orb-tools/dev-promote-prod:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-patch.*/
          orb-name: uraway/hello-world
          release: patch
      - orb-tools/dev-promote-prod:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-minor.*/
          orb-name: uraway/hello-world
          release: minor
      - orb-tools/dev-promote-prod:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-major.*/
          orb-name: uraway/hello-world
          release: major
