orbs:
  orb-tools: circleci/orb-tools@8.27.4

version: 2.1
workflows:
  promote-orb:
    jobs:
      - orb-tools/dev-promote-prod:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-patch.*/
          orb-name: uraway/hello-world
          release: patch
      - orb-tools/dev-promote-prod:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-minor.*/
          orb-name: uraway/hello-world
          release: minor
      - orb-tools/dev-promote-prod:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-major.*/
          orb-name: uraway/hello-world
          release: major
  publish-dev:
    jobs:
      - orb-tools/pack
      - orb-tools/publish-dev:
          requires: [orb-tools/pack]
          orb-name: uraway/hello-world
          checkout: true
          validate: true
      - orb-tools/trigger-integration-workflow:
          filters:
            branches:
              only: master
          requires: [orb-tools/publish-dev]
          tag: master
          ssh-fingerprints: 22:48:71:91:33:11:12:ab:f7:81:0f:1d:36:5a:44:34
