orbs:
  orb-tools: circleci/orb-tools@9.1.0

version: 2.1
workflows:
  publish-dev-orb:
    jobs:
      - orb-tools/publish-dev:
          checkout: true
          orb-path: ./src/orb.yml
          orb-name: uraway/hello-world
          validate: true
