default_filters: &default_filters
  branches:
    only: /.*/
  tags:
    only: /.*/

version: 2.1

parameters:
  dev-orb-version:
    default: 'dev:alpha'
    type: string
  run-integration-tests:
    type: boolean
    default: false

orbs:
  cli: circleci/circleci-cli@0.1.5
  hello-world: uraway/hello-world@<< pipeline.parameters.dev-orb-version >>

jobs:
  validation:
    executor: cli/default
    steps:
      - cli/install
      - checkout
      - run:
          name: バリデーション
          command: circleci orb validate ./src/orb.yml

  expansion:
    executor: cli/default
    steps:
      - cli/install
      - checkout
      - run:
          name: Install yq
          command: |
            sudo apt update && \
            sudo apt-get install jq python-pip python-dev && \
            sudo pip install yq
      - run:
          name: 展開テスト
          command: |
            result=$(circleci config process .circleci/test.yml | yq '.jobs."hello-world/echo-job".steps[0].run.command')
            echo ${result} | grep "Hello, CircleCI"

  execution:
    machine: true
    steps:
      - cli/install
      - checkout
      - run:
          name: 展開
          command: circleci config process .circleci/test.yml > .circleci/2.0.yml
      - run:
          name: ランタイムテスト
          command: circleci local execute --config .circleci/2.0.yml --job hello-world/echo-job | tee local_build_output.txt /dev/stderr | tail -n 1 | grep "Success"

  publish-dev:
    executor: cli/default
    steps:
      - cli/install
      - checkout
      - run:
          name: devバージョンを公開
          command: |
            circleci orb publish src/orb.yml uraway/hello-world@dev:alpha --token ${CIRCLE_TOKEN}
            circleci orb publish src/orb.yml uraway/hello-world@dev:${CIRCLE_SHA1:0:7} --token ${CIRCLE_TOKEN}

  dev-promote-prod:
    parameters:
      release:
        type: enum
        enum: [patch, minor, major]
        default: patch
        description: circleci orb publish promoteコマンドの引数
    executor: cli/default
    steps:
      - cli/install
      - checkout
      - run:
          name: dev:${CIRCLE_SHA1:0:7}を本番用Orbsへプロモートする
          command: circleci orb publish promote uraway/hello-world@dev:${CIRCLE_SHA1:0:7} << parameters.release >> --token ${CIRCLE_TOKEN}

  integration-test-for-orb:
    executor: hello-world/default
    steps:
      - hello-world/echo-command

  trigger-integration-test-workflow:
    executor: cli/default
    steps:
      - run:
          name: integration-testワークフローをトリガーする
          command: |
            VCS_TYPE=$(echo ${CIRCLE_BUILD_URL} | cut -d '/' -f 4)

            curl -u ${CIRCLE_TOKEN}: -X POST --header "Content-Type: application/json" -d "{
              \"branch\": \"${CIRCLE_BRANCH}\",
              \"parameters\": {\"run-integration-tests\": true, \"dev-orb-version\":\"dev:${CIRCLE_SHA1:0:7}\"}
            }" "https://circleci.com/api/v2/project/${VCS_TYPE}/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pipeline"

workflows:
  integration-test:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - integration-test-for-orb:
          filters: *default_filters
      - dev-promote-prod:
          requires: [integration-test-for-orb]
          filters:
            <<: *default_filters
            tags:
              only: /patch.*/
          release: patch
      - dev-promote-prod:
          requires: [integration-test-for-orb]
          filters:
            <<: *default_filters
            tags:
              only: /minor.*/
          release: minor
      - dev-promote-prod:
          requires: [integration-test-for-orb]
          filters:
            <<: *default_filters
            tags:
              only: /major.*/
          release: major
  validate_expansion_execution_publish-dev:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - validation:
          filters: *default_filters
      - publish-dev:
          requires: [validation]
          filters: *default_filters
      -  trigger-integration-test-workflow:
          requires: [publish-dev]
          filters: *default_filters
      # - expansion:
      #     requires: [publish-dev]
      #     filters:
      #       *default_filters
      # - execution:
      #     requires: [publish-dev]
      #     filters:
      #       *default_filters
