orbs:
  orb-tools: circleci/orb-tools@8.27.4

version: 2.1
workflows:
  publish-dev-orb:
    jobs:
      - orb-tools/pack:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-.*/
      - orb-tools/publish-dev:
          orb-name: uraway/hello-world
          validate: true
          requires:
              - orb-tools/pack
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-.*/
      - orb-tools/dev-promote-prod:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-patch.*/
          orb-name: uraway/hello-world
          release: patch
          requires:
              - orb-tools/publish-dev
      - orb-tools/dev-promote-prod:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-minor.*/
          orb-name: uraway/hello-world
          release: minor
          requires:
              - orb-tools/publish-dev
      - orb-tools/dev-promote-prod:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-major.*/
          orb-name: uraway/hello-world
          release: major
          requires:
              - orb-tools/publish-dev
