orbs:
  orb-tools: circleci/orb-tools@8.27.4

version: 2.1
workflows:
    promote-orb:
        jobs:
          - orb-tools/publish-dev:
              name: publish-dev
              orb-path: packed.yml
              orb-name: uraway/hello-world
              validate: true
          - orb-tools/dev-promote-prod:
              requires:
                  - publish-dev
              filters:
                branches:
                  ignore: /.*/
                tags:
                  only: /master-patch.*/
              orb-name: uraway/hello-world
              release: patch
          - orb-tools/dev-promote-prod:
              requires:
                  - publish-dev
              filters:
                branches:
                  ignore: /.*/
                tags:
                  only: /master-minor.*/
              orb-name: uraway/hello-world
              release: minor
          - orb-tools/dev-promote-prod:
              requires:
                  - publish-dev
              filters:
                branches:
                  ignore: /.*/
                tags:
                  only: /master-major.*/
              orb-name: uraway/hello-world
              release: major
