orbs:
  orb-tools: circleci/orb-tools@8.27.4

version: 2.1
workflows:
  publish-dev-orb:
    jobs:
      - orb-tools/pack
      - orb-tools/publish-dev:
          requires:
              - orb-tools/pack
          orb-path: ./src/orb.yml
          orb-name: yournamespace/your-orb
          validate: true
